<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Wawan">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Title -->
    <title>VX Production.</title>
    <!-- Place favicon.ico in the root directory -->
    <link rel="apple-touch-icon" href="images/logovx.png">
    <link rel="shortcut icon" type="image/ico" href="images/logovx.png" />
    <!-- Plugin-CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/linearicons.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="css/magnific-popup.css"> 
    <link rel="stylesheet" href="css/animate.css">

    
    <!-- Main-Stylesheets -->
    
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="css/responsive.css">
    <script src="js/vendor/modernizr-2.8.3.min.js"></script>
    <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
   
</head>

<body data-spy="scroll" data-target=".mainmenu-area">
    <!-- Preloader-content -->
    <div class="preloader">
        <span><i class="lnr lnr-sun"></i></span>
    </div>
    <!-- MainMenu-Area -->
    <nav class="mainmenu-area" data-spy="affix" data-offset-top="200">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary_menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="images/logovx1.png" class="d-inline-block align-top" alt="">
                </a>

            </div>
            <div class="collapse navbar-collapse" id="primary_menu">
                <ul class="nav navbar-nav mainmenu">
                    <li class="active"><a href="#home_page" >Beranda </a></li>
                    <li><a href="#about_page"               >Tentang Kami </a></li>
                    <li><a href="#features_page"            >Pelayanan</a></li>
                    <li><a href="#portfolio"                >Portofolio</a></li>
                    <li><a href="#price_page"               >Harga</a></li>
                    <li><a href="#contact_page"             >Kontak</a></li>
                </ul>
                <div class="right-button hidden-xs">
                    <a href="../../nescode/nescode/login_user.php">Login</a>
                </div>
            </div>
        </div>
    </nav>
    <!-- MainMenu-Area-End -->

<!-- Home-Area -->
    <header class="home-area overlay" id="home_page">
        <div class="container">
            <div class="row text-center" >
                <div class="col-xs-12 hidden-sm col-md-5">
                    <figure class="palak1 wow fadeInUp pt-5" data-wow-delay="0.2s">
                        <img src="images/palak1.png" alt="" style="padding-top:100px" >
                    </figure>
                </div>
                
                <div class="col-xs-12 col-md-7">
                    <div class="space-80 hidden-xs"></div>
                    <h1 class="wow fadeInUp" data-wow-delay="0.4s">Everything You Need <br>Is Only Here</h1>
                    <div class="space-20"></div>
                    <div class="desc wow fadeInUp" data-wow-delay="0.6s">
                        <p>Jasa pembuatan desain grafis terbaik untuk anda</p>
                    </div>
                    <div class="space-20"></div>
                    <a href="#price_page" class="bttn-white wow fadeInUp active" data-wow-delay="0.8s"><i class="lnr lnr-download"></i> Pesan Sekarang</a>
                </div>
            </div>
        </div>
    </header>
<!-- Home-Area-End -->

    <!-- About-Area -->
    <section class="section-padding" id="about_page">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-10 col-md-offset-1">
                    <div class="page-title text-center">
                        <img src="images/logovx.png" width="20%"  alt="About Logo">
                        <div class="space-20"></div>
                        <h5 class="title">About VX Production</h5>
                        <div class="space-30"></div>
                        <h3 class="blue-color">Jasa Desain Grafis Online terbaik untuk Pengembangan Bisnis Anda</h3>
                        <div class="space-20"></div>
                        <p>VX Production merupakan marketplace platform dengan ratusan desainer profesional yang siap membantu mewujudkan desain terbaik untuk kebutuhan branding bisnis Anda.
                                Kami berdiri sejak tahun 2017 dan telah berpengalaman dalam memberikan Jasa Pembuatan Desain Grafis kepada lebih dari 3000 Klien. Percayakan kepada kami untuk membuat bisnis anda semakin meningkat
                                dengan beragam keperluan Anda; mulai dari Website Design, Logo, Banner, Digital Imaging, Edit Gambar dan Photoshop, Presentasi, hingga Resume dan Portofolio. Jika membutuhkan desain 3D & perspektif, CAD Drawing, atau Infografis. 
                                Kami juga berkejasama dengan desainer grafis terbaik di bidangnya dan bisa diandalkan.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About-Area-End -->

    <!-- Fitur-Area -->
    <section class="feature-area section-padding-top" id="features_page">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                    <div class="page-title text-center">
                        <h5 class="title"> Pelayanan </h5>
                        <div class="space-10"></div>
                        <h3>Kenapa Anda Harus Memilih Kami ?</h3>
                        <div class="space-60"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12  justify-center col-md-4">
                    <div class="service-box wow fadeInUp" data-wow-delay="0.2s">
                        <div class="box-icon">
                            <i class="lnr lnr-rocket"></i>
                        </div>
                        <h4>Pengerjaan Cepat</h4>
                        <p>Anda tidak perlu menunggu lama untuk segera rebranding. Anda hanya butuh beberapa hari saja dan desain Anda sudah siap digunakan.
                    </div>
                    <div class="space-60"></div>
                    <div class="service-box wow fadeInUp" data-wow-delay="0.4s">
                        <div class="box-icon">
                            <i class="lnr lnr-paperclip"></i>
                        </div>
                        <h4>Dilengkapi Video Tutorial</h4>
                        <p>Desain buatan kami sudah dilengkapi dengan panduan berupa video tutorial. Jadi, segaptek apapun Anda. Jangan pernah takut, Anda pasti bisa.</p>
                    </div>
                    <div class="space-60"></div>
                    <div class="service-box wow fadeInUp" data-wow-delay="0.6s">
                        <div class="box-icon">
                            <i class="lnr lnr-cloud-download"></i>
                        </div>
                        <h4>Customize</h4>
                        <p>Kami bantu perubahan desain / rebranding untuk anda yang ingin selalu up to date desain logo perusahaan anda.</p>
                    </div>
                    <div class="space-60"></div>
                </div>
                <div class="hidden-xs hidden-sm col-md-4">
                    <figure class="mobile-image">
                        <img src="images/feature-image.png" alt="Feature Photo">
                    </figure>
                </div>

                <div class="col-xs-12  justify-center col-md-4">
                    <div class="service-box wow fadeInUp" data-wow-delay="0.2s">
                        <div class="box-icon">
                            <i class="lnr lnr-clock"></i>
                        </div>
                        <h4>Konsultasi</h4>
                        <p>Kami bukan sekedar penjual desain grafis, kami adalah IT Desain. Tugas utama kami adalah sebagai media konsultasi anda.</p>
                    </div>
                    <div class="space-60"></div>
                    <div class="service-box wow fadeInUp" data-wow-delay="0.4s">
                        <div class="box-icon">
                            <i class="lnr lnr-laptop-phone"></i>
                        </div>
                        <h4>Fully Responsive</h4>
                        <p>Website Design yang kami buat sepenuhnya responsive jadi bukan hanya dapat diakses di desktop tapi juga mobile dengan tampilan sama menariknya.</p>
                    </div>
                    <div class="space-60"></div>
                    <div class="service-box wow fadeInUp" data-wow-delay="0.6s">
                        <div class="box-icon">
                            <i class="lnr lnr-cog"></i>
                        </div>
                        <h4>Simple dan Professional</h4>
                        <p>Desain buatan kami simple akan tetapi tetap terlihat elegan dan professional</p>
                    </div>
                    <div class="space-60"></div>
                </div>
            </div>
        </div>
    </section>
    <!-- Feature-Area-End -->


    <!-- Testimonial-Area -->
    <section class="testimonial-area" id="testimonial_page">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title text-center">
                        <h5 class="title">Testimoni</h5>
                        <h3 class="dark-color">
                            Klien Mencintai Pekerjaan Kami</h3>
                        <div class="space-60"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="team-slide">
                        <div class="team-box">
                            <div class="team-image">
                                <img src="images/team-1.png" alt="">
                            </div>
                            <h4>Muhammad Sayyid</h4>
                            <h6 class="position">Pengusaha</h6>
                            <p>Mantap! Desain lebih efektif buat promosi daripada Yellow Pages.</p>
                        </div>
                        <div class="team-box">
                            <div class="team-image">
                                <img src="images/team-2.jpg" alt="">
                            </div>
                            <h4> Djanur Sasaongko </h4>
                            <h6 class="position">Home Industry</h6>
                            <p>Akhirnya bisa punya logo untuk perusahaan. Pelanggan datang sendiri.</p>
                        </div>
                        <div class="team-box">
                            <div class="team-image">
                                <img src="images/team-3.jpg" alt="">
                            </div>
                            <h4> Stefanie Poetri</h4>
                            <h6 class="position">Art Dirrector</h6>
                            <p>Logo perusahaan kami jadi lebih baik dan elegan dari sebelumnya, terimaksih banyak VX Production lov lov</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Testimonial-Area-End -->


<!-- portofolio-area -->
<section id="portfolio" class="portfolio pb-4" style="background-color: #5e88fc;"">
    <div class="container">
        <div class="row mb-4 pt-4">
            <div class="col">
                <h3 class="text-center" style="color:white"> Portofolio </h3>
            </div>
        </div>

        <div class="row mb-4 text-center">
            <div class="col-md">
                    <div class="card">
                            <img class="card-img-top" src="images/portofolio/p1.jpg" alt="Card image cap">
                            <div class="card-body">
                            <p class="card-text text-center" >Desain Logo dari mitra kami yang bernama skink</p>
                            </div>
                    </div>
            </div>
        
            <div class="col-md">
                    <div class="card">
                            <img class="card-img-top" src="images/portofolio/p2.jpg" alt="Card image cap">
                            <div class="card-body">
                            <p class="card-text">Desain Logo dari mitra kami yang bernama doit.io</p>
                            </div>
                    </div>
            </div>
    
            <div class="col-md">
                    <div class="card">
                            <img class="card-img-top" src="images/portofolio/p3.jpg" alt="Card image cap">
                            <div class="card-body">
                            <p class="card-text">Desain mackup brand Lotusana</p>
                            </div>
                    </div>
            </div>
        </div>
    
            <div class="row mb-4">
                <div class="col-md">
                        <div class="card">
                                <img class="card-img-top" src="images/portofolio/w4.jpg" alt="Card image cap">
                                <div class="card-body">
                                <p class="card-text">Custom desain dari pelanggan. ini merupakan website fasion desain untuk pria yang menjadi toko online yang paling besar pendapatannya di tahun 2019</p>
                                </div>
                        </div>
                </div>
            
                <div class="col-md">
                        <div class="card">
                                <img class="card-img-top" src="images/portofolio/d3.jpg" alt="Card image cap">
                                <div class="card-body">
                                <p class="card-text">contoh pembuatan poster kostuminasi</p>
                            </div>
                        </div>
                </div>
        
                <div class="col-md">
                        <div class="card">
                                <img class="card-img-top" src="images/portofolio/d.jpg" alt="Card image cap">
                                <div class="card-body">
                                <p class="card-text"> Pembuatan logo salah satu mitra kami yang merupakan salah satu perusahaan fast food paling terkenal didunia yang merajai pasar eropa</p>
                                </div>
                        </div>
                </div>
            </div>
        
            <div class="row mb-4">
                <div class="col-md">
                        <div class="card">
                                <img class="card-img-top" src="images/portofolio/d7.jpg" alt="Card image cap">
                                <div class="card-body">
                                <p class="card-text"> Logo mitra kerja kami dalam dunia pendidikan didunia maya yang merupakan startup terbaik tahun 2019</p>
                                </div>
                        </div>
                </div>
            
                <div class="col-md">
                        <div class="card">
                                <img class="card-img-top" src="images/portofolio/d6.jpg" alt="Card image cap">
                                <div class="card-body">
                                <p class="card-text">Desain sertifikat yang terdapat pada sebuah website pendidikan online yang menjadi best desain 2019 dalam acara ICS 2019 di Tiongkok</p>
                                
                            </div>
                        </div>
                </div>
        
                <div class="col-md">
                        <div class="card">
                                <img class="card-img-top" src="images/portofolio/d5.jpg" alt="Card image cap">
                                <div class="card-body">
                                <p class="card-text">Desain logo hasil karya vx production official yang terbaik tahun 2017-2019 serta menjadi desain grafis terbaik</p>
                                </div>
                        </div>
                </div>
            </div>
    </div>
    </section>
    <!-- end-portofolio-area -->



    <!--Price-Area -->
    <section class="section-padding price-area" id="price_page">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title text-center">
                        <h5 class="title">Harga</h5>
                        <h3 class="dark-color">Penawaran Harga Terbaik Kami</h3>
                        <div class="space-60"></div>
                    </div>
                </div>
            </div>
            <?php
                include_once("../../nescode/connection.php");
            ?>
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <div class="price-box">
                        <div class="price-header">
                            <div class="price-icon">
                                <span class="lnr lnr-rocket"></span>
                            </div>
                            <h4 class="upper">Basic (paket 1)</h4>
                        </div>
                        <div class="price-body">
                            <ul>
                                <li>1 Logo</li>
                                <li>1 Poster</li>
                                <li>2 Brosur</li>
                                <li>5 Infografis</li>
                                <li>1 katalog</li>
                            </ul>
                        </div>
                        <div class="price-rate">
                            <sup>Rp.</sup> <span class="rate">1 Juta</span>
                        </div>
                        <a href="../../nescode/checkout.php" class="bttn-white">Order Now</a> </td>
                            <!-- <a href="../../nescode/FormOrder.php" class="bttn-white">order</a> -->
                            
                        </div>
                    </div>
                    <div class="space-30 hidden visible-xs"></div>
                </div>

                <div class="col-xs-12 col-sm-4">
                    <div class="price-box">
                        <div class="price-header">
                            <div class="price-icon">
                                <span class="lnr lnr-diamond"></span>
                            </div>
                            <h4 class="upper">Pro (paket 2)</h4>
                        </div>
                        <div class="price-body">
                            <ul>
                                <li>2 Logo</li>
                                <li>2 Poster</li>
                                <li>3 Brosur</li>
                                <li>10 Infografis</li>
                                <li>2 katalog</li>
                            </ul>
                        </div>
                        <div class="price-rate">
                                <sup>Rp.</sup> <span class="rate">1,5 Juta</span>
                        </div>
                        <div class="price-footer">
                            <a href="../../nescode/checkout.php" class="bttn-white">order</a> 
                        </div>
                    </div>
                    <div class="space-30 hidden visible-xs"></div>
                </div>

                <div class="col-xs-12 col-sm-4">
                    <div class="price-box">
                        <div class="price-header">
                            <div class="price-icon">
                                <span class="lnr lnr-pie-chart"></span>
                            </div>
                            <h4 class="upper">Business (paket 3)</h4>
                        </div>
                        <div class="price-body">
                            <ul>
                                <li>3 Logo</li>
                                <li>5 Poster</li>
                                <li>5 Brosur</li>
                                <li>15 Infografis</li>
                                <li>5 katalog</li>
                            </ul>
                        </div>
                        <div class="price-rate">
                                <sup>Rp.</sup> <span class="rate">2 Juta</span>
                        </div>
                        <div class="price-footer">
                            <a href="../../nescode/checkout.php" class="bttn-white">order</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

            <div class="row" "> 
            <div class="col justify-align-center ">
                    <div class="price-box feed">
                        <div class="price-header">
                            <!-- <div class="price-icon">
                                <span class="lnr lnr-diamond"></span>
                            </div> -->
                            <h4 class="upper">Feedback</h4>
                            <p>Dapatkan semua penunjang pengembangan bisnis anda dari platfrom kami</p>
                        </div>
                        <div class="price-body">
                        <p> Dengan menggunakan jasa kami, Anda pasti mendapatkan:</p>
                            <ol style="margin-left:500px;">
                                <li style="text-align:left;">File master dalam format sesuai permintaan (AI, EPS, PDF)</li>
                                <li style="text-align:left;">File siap guna sesuai permintaan (PNG, Jpg, Jpeg)</li>
                                <li style="text-align:left;">Color Guidelines agar Anda tau kode warna pada logo</li>
                                <li style="text-align:left;">Font Guidelines agar Anda tau font yang digunakan pada logo</li>
                                <li style="text-align:left;">Jaminan backup ketika file desain anda hilang</li>
                            </ol>
                            <p>Apapun yang terbaik buat pengembangan bisnis anda !</p>
                    </div>
                    <div class="space-30 hidden visible-xs"></div>
                </div>
              </div>

    </section>
    <!--Price-Area-End -->



    <!-- Footer-Area -->
    <footer class="footer-area" id="contact_page">
        <div class="section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-title text-center">
                            <h5 class="title">Kontak kami</h5>
                            <h3 class="dark-color">Temukan Kami Dengan Detail Di Bawah Ini</h3>
                            <div class="space-60"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-box">
                            <div class="box-icon">
                                <span class="lnr lnr-map-marker"></span>
                            </div>
                            <p>Jl. Jend. Sudirman No.57, 20 Ilir D. I, Kec. Ilir<br />Kota Palembang, Sumatera Selatan 30151</p>
                        </div>
                        <div class="space-30 hidden visible-xs"></div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-box">
                            <div class="box-icon">
                                <span class="lnr lnr-phone-handset"></span>
                            </div>
                            <p>Wawan <br /> +62 93173370700</p>
                        </div>
                        <div class="space-30 hidden visible-xs"></div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-box">
                            <div class="box-icon">
                                <span class="lnr lnr-envelope"></span>
                            </div>
                            <p>VX Production <br /> official@vx-production.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Footer-Bootom -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-md-5">
                        <!-- footer -->
            <span>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved . By NESCODE</a></span>
            <!-- footer -->
                        <div class="space-30 hidden visible-xs"></div>
                    </div>
                    <div class="col-xs-12 col-md-7">
                        <div class="footer-menu">
                            <ul>
                                <li><a href="#">Tentang</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Fitur</a></li>
                                <li><a href="#">Harga</a></li>
                                <li><a href="#">Testimonial</a></li>
                                <li><a href="#">Kontak</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-Bootom-End -->
    </footer>
    <!-- Footer-Area-End -->




    <!--Vendor-JS-->
    <script src="js/vendor/jquery-1.12.4.min.js"></script>
    <script src="js/vendor/jquery-ui.js"></script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <!--Plugin-JS-->
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/contact-form.js"></script>
    <script src="js/ajaxchimp.js"></script>
    <script src="js/scrollUp.min.js"></script>
    <script src="js/magnific-popup.min.js"></script>
    <script src="js/wow.min.js"></script>
    <!--Main-active-JS-->
    <script src="js/main.js"></script>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>

</html>
